paths: {
    data_src: "/home/dataset/TotalSegmentor/Totalsegmentator_dataset/",
    data_dest: "/home/isaiah/TotalSegmentator/demo3/",
    metadata_src: "/home/dataset/TotalSegmentor/meta.csv",
    labels_src: "/home/isaiah/TotalSegmentatorProj/metadata/classes.json",
    model_load_src: null,
    model_ckpts_dest: "/home/isaiah/TotalSegmentator/results/20230329/demo_nnunet_ckpt_02.pth",
    model_best_dest: "/home/isaiah/TotalSegmentator/results/20230329/demo_nnunet_best_02.pth",
    train_report_path: "/home/isaiah/TotalSegmentator/results/20230329/demo_nnunet_train_reps_02",
    eval_report_path: "/home/isaiah/TotalSegmentator/results/20230329/demo_nnunet_eval_reps_02",
}

preprocess_params: {
    ignore_existing_files: True,
    init_downsample_ratio: 2.5,
    intensity_range: [-1024, 2048],
    resolution: [224, 224],
    normalization: True,
    pack_bits: True,
}

train_dataset_params: {
    augmentations: ["center_crop", "pad_to_size"],
    scaling_factors: 0.1,
    rotation_angles: 10.,
    gamma_range: [-0.3, 0.3],
    model_shrinking_factor: 128,
    num_control_points: 7,
    max_displacement: 3.,
    labels: [],
    file_extension: "npz",
}

validation_dataset_params: {
    augmentations: ["center_crop", "pad_to_size"],
    scaling_factors: 0.1,
    rotation_angles: 10.,
    gamma_range: [-0.3, 0.3],
    model_shrinking_factor: 128,
    num_control_points: 7,
    max_displacement: 3.,
    labels: [],
    file_extension: "npz",
}

optimizer_params: {
    lr: 0.1,
    weight_decay: 1.0e-3,
}

scheduler_params: {
    base_lr: 1.0e-2,
    max_lr: 1.0e-5,
    step_size_up: 40,
    mode: "triangular",
    gamma: 0.998,
    cycle_momentum: False,
}

model_params: {
    channels: [1, 32, 64, 128, 256, 320],
    num_classes: 105,
}

run_params: {
    model: "nnunet",
    train: True,
    optimizer: "adamw",
    scheduler: null,
    metric: "dice",
    disable_cuda: False,
    epochs: 1000,
    batch_size: 1,
    validation_size: 1,
    tracking_frequency: 1,
    loss_weights: [1., 10.],
    loss_weights_decay: [0.95, 1.],
    label_weights: [0.75, 0.14, 0.07, 0.04],
    num_classes: 106,
}
